# Generated by Django 5.0.3 on 2024-03-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_alter_donation_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donator',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
